# Generated by Django 5.1.3 on 2024-11-29 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_cartitem_unique_together_cartitem_session_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='book',
            name='preview_file',
            field=models.FileField(blank=True, null=True, upload_to='book_previews/'),
        ),
    ]
